#!/usr/bin/env python
"""Generate CORPUS_CONTENTS.md — the source-of-truth list of every work that is
actually extracted, chunked, and embedded in the pipeline.

Grounded in 04_processed/chunks.jsonl (what got chunked) cross-checked against
04_processed/embeddings/manifest.json (what got embedded). This is authoritative
over 03_catalog/catalog.yaml, which only tracks the most recent batch.

Regenerate after every ingestion:
    python tools/build_corpus_manifest.py
"""
import json, collections, pathlib, datetime

ROOT = pathlib.Path(__file__).resolve().parent.parent
CHUNKS = ROOT / "04_processed/chunks.jsonl"
MANIFEST = ROOT / "04_processed/embeddings/manifest.json"
OUT = ROOT / "CORPUS_CONTENTS.md"

KIND_ORDER = ["canonical", "biography", "athvani", "periodical", "reference"]


def load():
    works = collections.OrderedDict()
    n = 0
    for line in CHUNKS.open():
        d = json.loads(line)
        n += 1
        wid = d["work_id"]
        w = works.get(wid)
        if w is None:
            w = works[wid] = {
                "kind": d.get("kind", ""), "author": d.get("author", "") or "—",
                "work_type": d.get("work_type", ""), "title": d.get("title", "") or wid,
                "langs": set(), "chunks": 0, "path": d.get("source_path", ""),
            }
        w["langs"].add(d.get("language", ""))
        w["chunks"] += 1
    return works, n


def main():
    works, n_chunks = load()
    manifest = json.loads(MANIFEST.read_text()) if MANIFEST.exists() else {}
    embedded = manifest.get("chunk_count")
    consistent = embedded == n_chunks and manifest.get("complete")

    by_kind = collections.defaultdict(list)
    for wid, w in works.items():
        by_kind[w["kind"]].append((wid, w))

    today = datetime.date.today().isoformat()
    L = []
    L.append("# Corpus Contents — Source of Truth\n")
    L.append(
        "> Auto-generated by `tools/build_corpus_manifest.py` from "
        "`04_processed/chunks.jsonl` (what is chunked) cross-checked against "
        "`04_processed/embeddings/manifest.json` (what is embedded).\n"
        "> **This file — not `03_catalog/catalog.yaml` — is authoritative for "
        "“what is retrievable right now.”** Regenerate after every ingestion.\n"
    )
    L.append(f"_Generated: {today}_\n")

    # Summary
    kind_chunks = collections.Counter()
    kind_works = collections.Counter()
    lang_chunks = collections.Counter()
    for wid, w in works.items():
        kind_chunks[w["kind"]] += w["chunks"]
        kind_works[w["kind"]] += 1
    for line in CHUNKS.open():
        d = json.loads(line)
        lang_chunks[d.get("language", "?")] += 1

    L.append("## At a glance\n")
    L.append(f"- **{len(works)} works**, **{n_chunks:,} chunks**, embedding model "
             f"`{manifest.get('model', '?')}` (dim {manifest.get('dim', '?')}).")
    emb_state = (f"✅ all {embedded:,} chunks embedded (manifest `complete`)"
                 if consistent else
                 f"⚠️ manifest says {embedded} embedded vs {n_chunks} chunked — re-run embedder")
    L.append(f"- **Embedding status:** {emb_state}.")
    L.append(f"- **By kind:** " + ", ".join(
        f"{k} {kind_works[k]}w/{kind_chunks[k]:,}c" for k in KIND_ORDER if kind_works[k]) + ".")
    L.append(f"- **By language (chunks):** " + ", ".join(
        f"{lg} {c:,}" for lg, c in lang_chunks.most_common()) + ".\n")

    # Per-kind tables
    for kind in KIND_ORDER + sorted(set(by_kind) - set(KIND_ORDER)):
        rows = by_kind.get(kind)
        if not rows:
            continue
        rows.sort(key=lambda x: (x[1]["author"], -x[1]["chunks"]))
        L.append(f"## {kind.capitalize()} "
                 f"({len(rows)} works, {kind_chunks[kind]:,} chunks)\n")
        L.append("| Work | Author / source | Type | Lang | Chunks |")
        L.append("|---|---|---|---|---:|")
        for wid, w in rows:
            langs = ",".join(sorted(l for l in w["langs"] if l)) or "?"
            title = w["title"].replace("|", "\\|")
            L.append(f"| {title} (`{wid}`) | {w['author']} | "
                     f"{w['work_type'] or '—'} | {langs} | {w['chunks']} |")
        L.append("")

    OUT.write_text("\n".join(L) + "\n")
    print(f"Wrote {OUT} — {len(works)} works, {n_chunks:,} chunks. consistent={consistent}")


if __name__ == "__main__":
    main()
